### ISSUE TITLE
Can' disband my federation of clusters

### ISSUE THREAD

**Issue by ManuLazarus** [StackPointCloud/stackpoint.io#1]
Hi,

I've been playing arround with federations and they are really easy to set up and work very well. Gratz!

I found a problem trying to disband one of the federations I've creater, thoug. Its name is "SPC Old Wave" Federation". As workarround I tried to delete the clusters of that federation but the cluster "SPC Lively Unit" (GCE Europe West  1b) seems to be stacked as well.

Could you delete both "SPC Old Wave" federation and "SPC Lively Unit" cluster.
Thanks in advance.

Cheers,
Manu

**Comment by odacremolbap** [comment]
Thanks for the issue @ManuLazarus 

The cluster has been set to deleted. Please, make sure your instances are deleted from GCE. If that's not the case we can set the cluster to running, so you can delete it again.

You hit two different issues here:

Delete cluster: might be related to an operation related to the disk of our worker instance that executed the federation disband. We are working on a *retry* feature that lets you execute failed operations.

Disband: I think we found the issue. We will fix, test and deploy.

Thanks!

**Comment by ManuLazarus** [comment]
Thanks to you @odacremolbap.

By the way I have a similar issue with the cluster "SPC Icy Cloud" (GCE Europe West 1b). It seems got stucked during its deletion.

Cheers,
Manu

**Comment by odacremolbap** [comment]
Both clusters have not been deleted, can you please access the GCE console to remove the instances?

We are trying to figure out the problem, since there is no space issue now with those jobs.
The disband fix has already been deployed to production.

We will remove the **deleting** cluster in a while (we want to let you some time if you need to locate the instance at GCE)

**Comment by ManuLazarus** [comment]
I've just deleted both of them.

Regards,
Manu

**Comment by odacremolbap** [comment]
@ManuLazarus this seems to be an issue with etcd-operators (a third party resource) and kubernetes garbage collector, which is fairly new

Our federation solution is being affected by this issue, we already have a workaround but need to test it further.

**Comment by arieljatib** [comment]
fix deployed.
