### ISSUE TITLE
Need access to us-east-2 (ohio) and new i3 instances

### ISSUE THREAD

**Issue by TimMeade** [StackPointCloud/stackpoint.io#5]
New region us-east-2 in ohio and new I3 instances look like they might be the best cost/perf value.

Thanks

Tim

**Comment by arieljatib** [comment]
Hi @TimMeade - thanks for the suggestion. I was not aware of the new I3 instances. 

https://aws.amazon.com/about-aws/whats-new/2016/11/coming-soon-amazon-ec2-i3-instances-next-generation-storage-optimized-high-io-instances/

**Comment by baldwinSPC** [comment]
Ohio has been there for awhile. We're backlogging i3 instances for a few reasons.
