### ISSUE TITLE
Cannot select custom SSH key

### ISSUE THREAD

**Issue by elsteelbrain** [StackPointCloud/stackpoint.io#8]
While creating a new cluster, when I select my own SSH key and click "Submit", the space in front of  "fingerprint' icon in the left bar is empty. Which means that the custom key was not selected. I went back and selected it again, but it gave same result. If I go ahead and create cluster, it just uses default SCP key. I deleted the default key, so, it always selects my custom key now.

**Comment by arieljatib** [comment]
@tarequeh is this something requiring a fix on the front end?

**Comment by tarequeh** [comment]
@arieljatib The key is actually selected and correctly sent when cluster creation request is submitted, only the name is not displayed in the sidebar due to a bug. Adding a fix.

**Comment by tarequeh** [comment]
This is no longer an issue and we can close it.
